export const POLICY = {
  APY_CAP_PCT: 500,
  MIN_TVL_USD: 1_000_000,
  RISK_SCORE_DEPLOY_MAX: 75,
  RISK_SCORE_EXIT_MIN: 85,
  DD_REDUCE_MAX: 1.5,
  DD_EXIT_MAX: 0.8,
  SLIPPAGE_MAX_PCT_CONSERVATIVE: 0.5,
  SLIPPAGE_MAX_PCT_BALANCED: 1.0,
  POSITION_MAX_PCT_PER_POOL_CONSERVATIVE: 25,
  POSITION_MAX_PCT_PER_POOL_BALANCED: 35,
  POSITION_MAX_PCT_PER_VENUE_CONSERVATIVE: 50,
  POSITION_MAX_PCT_PER_VENUE_BALANCED: 60,
} as const;

export const RISKY_TOKEN_BLACKLIST = [
  "DOG",
  "PEPE",
  "FLOKI",
  "SHIB",
  "MEME",
  "DEGEN",
  "BRETT",
  "MOG",
  "WOJAK",
  "INU",
] as const;
